### ISSUE TITLE
Launchlibrary returns unknown 

### ISSUE THREAD

**Issue by YoshiFan501** [HalfDecent/HA-Custom_components#5]
copying your code without editing it into my hassio and running it only shows it as unknown

**Comment by teslasmoustache** [comment]
Did you place the file in the right directory?

**Comment by YoshiFan501** [comment]
config/custom_components/sensor yes

**Comment by teslasmoustache** [comment]
Oh. Actually, I am getting the same error. It looks like something is wrong with launchlibrary.net right now.

**Comment by YoshiFan501** [comment]
alright. thank you for letting me know!

**Comment by teslasmoustache** [comment]
Wait a second. That was a browser error....I don't know what's going on...

**Comment by ludeeus** [comment]
It works now, but I see that there has been an issue where the next launch did not have a name.
Will look into that

**Comment by ludeeus** [comment]
For some reason the structure of their API changed...
It is fixed here:
https://gitlab.com/custom_components/ludeeus/launchlibrary
